### ISSUE TITLE
Spam error to console

### ISSUE THREAD

**Issue by zekicks** [nulli0n/ExcellentEnchants-spigot#102]
`[08:59:42 ERROR]: Could not pass event EntityDamageByEntityEvent to ExcellentEnchants v4.0.2
java.lang.NoSuchFieldError: Class org.bukkit.Registry does not have member field 'org.bukkit.Registry EFFECT'
        at su.nightexpress.excellentenchants.enchantment.impl.weapon.SurpriseEnchant.onAttack(SurpriseEnchant.java:86) ~[ExcellentEnchants-4.0.2.jar:?]
        at su.nightexpress.excellentenchants.enchantment.registry.wrapper.DataGathers$6.useEnchant(DataGathers.java:229) ~[ExcellentEnchants-4.0.2.jar:?]
        at su.nightexpress.excellentenchants.enchantment.registry.wrapper.DataGathers$6.useEnchant(DataGathers.java:202) ~[ExcellentEnchants-4.0.2.jar:?]
        at su.nightexpress.excellentenchants.enchantment.registry.wrapper.WrappedEvent.lambda$execute$0(WrappedEvent.java:54) ~[ExcellentEnchants-4.0.2.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.registry.wrapper.WrappedEvent.lambda$execute$1(WrappedEvent.java:48) ~[ExcellentEnchants-4.0.2.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.registry.wrapper.WrappedEvent.execute(WrappedEvent.java:47) ~[ExcellentEnchants-4.0.2.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2060]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1227) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1080) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1023) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1261) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2260) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1479) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.hurt(Animal.java:88) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1359) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2302) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:3010) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2932) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by nulli0n** [comment]
Fixed in v4.0.4
