### ISSUE TITLE
Failed to Load on 1.16.5

### ISSUE THREAD

**Issue by JinOuYongGu** [nulli0n/ExcellentEnchants-spigot#11]
Env:
- ExcellentEnchants v3.1.4
- git-Paper-792 (MC: 1.16.5)

[21:36:33 INFO]: [NexEngine] Enabling NexEngine v2.1.2 build-15/03/2022
[21:36:33 INFO]: [NexEngine] Loaded NMS version: V1_16_R3
[21:36:33 INFO]: [NexEngine] Successfully hooked with LuckPerms permissions
[21:36:33 INFO]: [NexEngine] Successfully hooked with EssentialsX Economy economy
[21:36:33 INFO]: [NexEngine] Successfully hooked with LuckPerms chat
[21:36:33 INFO]: [NexEngine] Successfully hooked with Vault!
[21:36:33 INFO]: [NexEngine] Found 0 external module(s).
[21:36:33 INFO]: [NexEngine] Plugin loaded in 106 ms!
[21:36:33 INFO]: [ExcellentEnchants] Enabling ExcellentEnchants v3.1.4
[21:36:33 INFO]: [ExcellentEnchants] Powered by: NexEngine
[21:36:33 INFO]: [ExcellentEnchants] Tiers Loaded: 5
[21:36:33 INFO]: [ExcellentEnchants] Found 0 external module(s).
[21:36:33 WARN]: [NexEngine] Loaded class su.nightexpress.excellentenchants.nms.V1_16_R3 from ExcellentEnchants v3.1.4 which is not a depend, softdepend or loadbefore of this plugin.
[21:36:33 ERROR]: [ExcellentEnchants] [Smelter] Invalid source material 'RAW_IRON' !
[21:36:33 ERROR]: [ExcellentEnchants] [Smelter] Invalid source material 'RAW_GOLD' !
[21:36:33 ERROR]: [ExcellentEnchants] [Smelter] Invalid source material 'RAW_COPPER' !
[21:36:33 ERROR]: Error occurred while enabling ExcellentEnchants v3.1.4 (Is it up to date?)
**java.lang.NoSuchFieldError: INFESTED_DEEPSLATE
        at su.nightexpress.excellentenchants.manager.enchants.tool.EnchantTelekinesis.<clinit>(EnchantTelekinesis.java:40) ~[?:?]**
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at su.nightexpress.excellentenchants.manager.EnchantRegister.init(EnchantRegister.java:204) ~[?:?]
        at su.nightexpress.excellentenchants.manager.EnchantRegister.<clinit>(EnchantRegister.java:99) ~[?:?]
        at su.nightexpress.excellentenchants.manager.EnchantManager.onLoad(EnchantManager.java:47) ~[?:?]
        at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:21) ~[?:?]
        at su.nightexpress.excellentenchants.ExcellentEnchants.enable(ExcellentEnchants.java:46) ~[?:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:178) ~[?:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:78) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Unknown Source) [?:?]
[21:36:33 INFO]: [ExcellentEnchants] Disabling ExcellentEnchants v3.1.4
[21:36:33 ERROR]: Error occurred while disabling ExcellentEnchants v3.1.4 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class su.nightexpress.excellentenchants.manager.EnchantRegister
        at su.nightexpress.excellentenchants.manager.EnchantManager.onShutdown(EnchantManager.java:74) ~[?:?]
        at su.nexmedia.engine.api.manager.AbstractManager.shutdown(AbstractManager.java:28) ~[?:?]
        at su.nightexpress.excellentenchants.ExcellentEnchants.disable(ExcellentEnchants.java:52) ~[?:?]
        at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:194) ~[?:?]
        at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:84) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Purpur-1171]

**Comment by nulli0n** [comment]
Fixed.
