### ISSUE TITLE
 Error occurred while enabling ExcellentEnchants v4.1.0 

### ISSUE THREAD

**Issue by sky-3311** [nulli0n/ExcellentEnchants-spigot#117]
[14:34:38 ERROR]: Error occurred while enabling ExcellentEnchants v4.1.0 (Is it up to date?)
java.lang.IllegalStateException: This registry can't create intrusive holders
        at net.minecraftforge.registries.NamespacedWrapper.m_203693_(NamespacedWrapper.java:364) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
        at su.nightexpress.excellentenchants.nms.v1_20_R1.V1_20_R1.registerEnchantment(V1_20_R1.java:80) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.registry.EnchantRegistry.register(EnchantRegistry.java:234) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.registry.EnchantRegistry.onLoad(EnchantRegistry.java:81) ~[?:?]
        at su.nightexpress.nightcore.manager.SimpleManager.setup(SimpleManager.java:20) ~[?:?]
        at su.nightexpress.excellentenchants.EnchantsPlugin.enable(EnchantsPlugin.java:73) ~[?:?]
        at su.nightexpress.nightcore.NightPlugin.loadManagers(NightPlugin.java:150) ~[?:?]
        at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:56) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.3.5-universal.jar%23203!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:851) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:282) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by nulli0n** [comment]
![изображение](https://github.com/user-attachments/assets/7d2da497-0b93-4a7d-9bd6-d0fff3975f12)
