### ISSUE TITLE
Excellent enchants not working when loading Survivalist enchantment

### ISSUE THREAD

**Issue by MCKoningSander** [nulli0n/ExcellentEnchants-spigot#122]
Hey man like in the title the plugin doesnt work when the survivalist enchantment file is being made, all dependencies are up to date and plugin is on newest version. i whould greatly appreciate if u helped me with this error.

Error:
[17:45:40] [Server thread/ERROR]: Error occurred while enabling ExcellentEnchants v4.1.0 (Is it up to date?)
java.lang.IllegalArgumentException: Recipe must have non-AIR result.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.CraftingRecipe.<init>(CraftingRecipe.java:21) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftComplexRecipe.<init>(CraftComplexRecipe.java:17) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.item.crafting.IRecipeComplex.toBukkitRecipe(IRecipeComplex.java:43) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolder.java:16) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:24) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:10) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.impl.fishing.SurvivalistEnchant.loadAdditional(SurvivalistEnchant.java:45) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.data.AbstractEnchantmentData.onLoad(AbstractEnchantmentData.java:260) ~[?:?]
        at su.nightexpress.nightcore.manager.AbstractFileData.load(AbstractFileData.java:36) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.registry.EnchantRegistry.load(EnchantRegistry.java:243) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.registry.EnchantRegistry.register(EnchantRegistry.java:232) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.registry.EnchantRegistry.onLoad(EnchantRegistry.java:84) ~[?:?]
        at su.nightexpress.nightcore.manager.SimpleManager.setup(SimpleManager.java:20) ~[?:?]
        at su.nightexpress.excellentenchants.EnchantsPlugin.enable(EnchantsPlugin.java:73) ~[?:?]
        at su.nightexpress.nightcore.NightPlugin.loadManagers(NightPlugin.java:150) ~[?:?]
        at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:56) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.reload(CraftServer.java:1012) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.Bukkit.reload(Bukkit.java:870) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServer.java:921) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:414) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1842) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$7(PlayerConnection.java:1818) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.util.thread.IAsyncTaskHandler.bB(SourceFile:121) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1213) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]

**Comment by nulli0n** [comment]
Perhaps a plugin conflict. Disable other plugins and try again. And update to v4.2.0
