### ISSUE TITLE
Command exception: /ecoenchants:ecoenchants gui

### ISSUE THREAD

**Issue by xiaofengv233** [nulli0n/ExcellentEnchants-spigot#138]
Command exception: /ecoenchants:ecoenchants gui
org.bukkit.command.CommandException: Unhandled exception executing command 'ecoenchants:ecoenchants' in plugin EcoEnchants v12.18.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property menu has not been initialized
        at EcoEnchants v12.18.7.jar/com.willfp.ecoenchants.enchant.EnchantGUI.openGUI(EnchantGUI.kt:149) ~[EcoEnchants v12.18.7.jar:?]
        at EcoEnchants v12.18.7.jar/com.willfp.ecoenchants.commands.CommandGUI.onExecute(CommandGUI.kt:12) ~[EcoEnchants v12.18.7.jar:?]
        at eco-6.74.1-all.jar/com.willfp.eco.internal.command.HandledCommand.handleExecution(HandledCommand.kt:110) ~[eco-6.74.1-all.jar:?]
        at eco-6.74.1-all.jar/com.willfp.eco.internal.command.HandledCommand.handleExecution(HandledCommand.kt:101) ~[eco-6.74.1-all.jar:?]
        at eco-6.74.1-all.jar/com.willfp.eco.internal.command.HandledCommand.onCommand(HandledCommand.kt:41) ~[eco-6.74.1-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 27 more

**Comment by nulli0n** [comment]
Please at least read what you report and where.
