### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [nulli0n/ExcellentEnchants-spigot#146]
31:00 INFO]: This server is running Paper version 1.21.3-38-master@de6173b (2024-11-18T20:19:00Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are 18 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.3-29-be886cf (MC: 1.21.3)

 Server Plugins (24):
[13:31:26 INFO]: Paper Plugins:
[13:31:26 INFO]:  - EconomyShopGUI
[13:31:26 INFO]: Bukkit Plugins:
[13:31:26 INFO]:  - BetterRTP, ChatManager, Citizens, DamageIndicator, Essentials, ExcellentEnchants, floodgate, LagFixer, LuckPerms, nightcore
[13:31:26 INFO]:  PL-Hide, PlaceholderAPI, ProtocolLib, RedProtect, SafeNET, SetSpawn, Themis, Vault, ViaBackwards, ViaVersion
[13:31:26 INFO]:  WorldEdit, WorldGuard, WorldGuardExtraFlags

13:28:25 ERROR]: Could not pass event BlockDropItemEvent to ExcellentEnchants v4.3.0
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:BLOCK_LAVA_EXTINGUISH
        at net.minecraft.resources.ResourceLocation.assertValidPath(ResourceLocation.java:278) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.resources.ResourceLocation.withDefaultNamespace(ResourceLocation.java:68) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.resources.ResourceLocation.bySeparator(ResourceLocation.java:92) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.resources.ResourceLocation.parse(ResourceLocation.java:64) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at org.bukkit.craftbukkit.CraftWorld.playSound(CraftWorld.java:1935) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at org.bukkit.craftbukkit.CraftWorld.playSound(CraftWorld.java:1911) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at org.bukkit.craftbukkit.CraftWorld.playSound(CraftWorld.java:1901) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at nightcore-2.7.2.jar/su.nightexpress.nightcore.util.wrapper.UniSound.play(UniSound.java:92) ~[nightcore-2.7.2.jar:?]
        at ExcellentEnchants-4.3.0.jar/su.nightexpress.excellentenchants.enchantment.impl.tool.SmelterEnchant.onDrop(SmelterEnchant.java:143) ~[ExcellentEnchants-4.3.0.jar:?]
        at ExcellentEnchants-4.3.0.jar/su.nightexpress.excellentenchants.registry.wrapper.DataGathers$2.useEnchant(DataGathers.java:76) ~[ExcellentEnchants-4.3.0.jar:?]
        at ExcellentEnchants-4.3.0.jar/su.nightexpress.excellentenchants.registry.wrapper.DataGathers$2.useEnchant(DataGathers.java:55) ~[ExcellentEnchants-4.3.0.jar:?]
        at ExcellentEnchants-4.3.0.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.lambda$execute$0(WrappedEvent.java:48) ~[ExcellentEnchants-4.3.0.jar:?]
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) ~[?:?]
        at ExcellentEnchants-4.3.0.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.lambda$execute$1(WrappedEvent.java:44) ~[ExcellentEnchants-4.3.0.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at ExcellentEnchants-4.3.0.jar/su.nightexpress.excellentenchants.registry.wrapper.WrappedEvent.execute(WrappedEvent.java:43) ~[ExcellentEnchants-4.3.0.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockDropItemEvent(CraftEventFactory.java:471) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:456) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:340) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:304) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1870) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1497) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1507) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1343) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-38-de6173b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by nulli0n** [comment]
Fixed in v4.3.1
