### ISSUE TITLE
Unable to log in to the server + Error message

### ISSUE THREAD

**Issue by BigAppleClass** [nulli0n/ExcellentEnchants-spigot#147]
This server is running CraftBukkit version 4392-Spigot-60c9969-f282231 (MC: 1.21.3) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

Unable to log in to the server
[05:50:33] [User Authenticator #1/INFO]: UUID of player Naive_god is 013ecfbf-8055-3f84-8be4-9d00700523b6
[05:50:33] [Server thread/ERROR]: Failed to handle packet ServerboundSelectKnownPacks[knownPacks=[minecraft:core:1.21.3]], suppressing error
java.lang.IllegalStateException: Tags already present before freezing
        at net.minecraft.core.RegistryMaterials.n(SourceFile:317) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.core.IRegistryCustom$d.c(SourceFile:37) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.minecraft.core.IRegistryCustom$c.<init>(SourceFile:65) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.core.IRegistryCustom$a.<init>(SourceFile:106) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.core.IRegistryCustom.e(SourceFile:110) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.core.LayeredRegistryAccess.a(SourceFile:63) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.core.LayeredRegistryAccess.c(SourceFile:59) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.network.config.SynchronizeRegistriesTask.a(SourceFile:39) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.network.config.SynchronizeRegistriesTask.a(SourceFile:47) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:140) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.network.protocol.configuration.ServerboundSelectKnownPacks.a(SourceFile:27) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.network.protocol.configuration.ServerboundSelectKnownPacks.a(SourceFile:12) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:164) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1319) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:210) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:138) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1298) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1291) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:147) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1248) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.x_(MinecraftServer.java:1258) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1101) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[05:50:37] [Server thread/INFO]: com.mojang.authlib.GameProfile@7264f66d[id=013ecfbf-8055-3f84-8be4-9d00700523b6,name=Naive_god,properties={}] lost connection: Disconnected
[05:51:28] [Server thread/INFO]: Server empty for 60 seconds, pausing

 Error message
[05:50:26] [Server thread/ERROR]: Error occurred while enabling ExcellentEnchants v4.3.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
        at java.base/java.util.HashMap.putMapEntries(HashMap.java:503) ~[?:?]
        at java.base/java.util.HashMap.<init>(HashMap.java:492) ~[?:?]
        at su.nightexpress.excellentenchants.nms.Internal_1_21_3.getTagsMap(Internal_1_21_3.java:110) ~[?:?]
        at su.nightexpress.excellentenchants.nms.Internal_1_21_3.freeze(Internal_1_21_3.java:139) ~[?:?]
        at su.nightexpress.excellentenchants.nms.Internal_1_21_3.freezeRegistry(Internal_1_21_3.java:121) ~[?:?]
        at su.nightexpress.excellentenchants.registry.EnchantRegistry.onLoad(EnchantRegistry.java:180) ~[?:?]
        at su.nightexpress.nightcore.manager.SimpleManager.setup(SimpleManager.java:20) ~[?:?]
        at su.nightexpress.excellentenchants.EnchantsPlugin.enable(EnchantsPlugin.java:64) ~[?:?]
        at su.nightexpress.nightcore.NightPlugin.loadManagers(NightPlugin.java:135) ~[?:?]
        at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4392-Spigot-60c9969-f282231]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[05:50:26] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

**Comment by nulli0n** [comment]
Fixed in v5.0.0
