### ISSUE TITLE
where to download

### ISSUE THREAD

**Issue by BigAppleClass** [nulli0n/ExcellentEnchants-spigot#18]
[20:08:48 INFO]: Paper: Using Java cipher from Velocity.
[20:08:49 ERROR]: Could not load 'plugins\ExcellentEnchants-3.2.4.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [NexEngine]. Please download and install these plugins to run 'ExcellentEnchants'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:287) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:421) ~[paper-1.19.1.jar:git-Paper-102]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.1.jar:git-Paper-102]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-102]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-102]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:08:49 INFO]: [LuckPerms] Loading LuckPerms v5.4.36

**Comment by nulli0n** [comment]
On the plugin page.
