### ISSUE TITLE
Console error spam caused by enchantments

### ISSUE THREAD

**Issue by BambuiZepelin** [nulli0n/ExcellentEnchants-spigot#2]
Sonic 
Bunny Hop
Aqua man
Night Vision
Haste 

These enchantments cause a st
[Errors.txt](https://github.com/nulli0n/ExcellentEnchants-spigot/files/7919037/Errors.txt)
ream of errors for as long as I wear the item or have it in hand. Some don't even work at all.
I use EEnchants v3.1.0 With the engine it came with and Purpur 1522 (1.18.1)
I did not modify anything from the plugin either so it is very strange for me to understand this issue. It will happen no matt
[Errors.txt](https://github.com/nulli0n/ExcellentEnchants-spigot/files/7919038/Errors.txt)
er what level the enchant is. 
I even went into the purpur configs and switched "allow-unsafe-enchants:"  to true, in hopes it will change anything.

The Error: https://pastebin.com/jhKVrDxb

**Comment by nulli0n** [comment]
Should be fixed in the latest update.

**Comment by NyaomiDEV** [comment]
Reporting from version 3.1.1 and Paper 1.18.1: nope, it spawns this error:
```
[03:11:12 FATAL]: Thread Craft Scheduler Thread - 8 - ExcellentEnchants failed main thread check: Chunk getEntities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.18.1.jar:git-Paper-176]
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2328) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftWorld.getNMSEntities(CraftWorld.java:1017) ~[paper-1.18.1.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_18_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:425) ~[paper-1.18.1.jar:git-Paper-176]
	at su.nightexpress.excellentenchants.manager.tasks.AbstractEnchantPassiveTask.lambda$getEntities$1(AbstractEnchantPassiveTask.java:51) ~[ExcellentEnchants-3.1.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at su.nightexpress.excellentenchants.manager.tasks.AbstractEnchantPassiveTask.getEntities(AbstractEnchantPassiveTask.java:50) ~[ExcellentEnchants-3.1.1.jar:?]
	at su.nightexpress.excellentenchants.manager.tasks.AbstractEnchantPassiveTask.action(AbstractEnchantPassiveTask.java:27) ~[ExcellentEnchants-3.1.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-176]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-176]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
>....
[03:11:12 WARN]: [ExcellentEnchants] Plugin ExcellentEnchants v3.1.1 generated an exception while executing task 13
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.18.1.jar:git-Paper-176]
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2328) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftWorld.getNMSEntities(CraftWorld.java:1017) ~[paper-1.18.1.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_18_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:425) ~[paper-1.18.1.jar:git-Paper-176]
	at su.nightexpress.excellentenchants.manager.tasks.AbstractEnchantPassiveTask.lambda$getEntities$1(AbstractEnchantPassiveTask.java:51) ~[ExcellentEnchants-3.1.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at su.nightexpress.excellentenchants.manager.tasks.AbstractEnchantPassiveTask.getEntities(AbstractEnchantPassiveTask.java:50) ~[ExcellentEnchants-3.1.1.jar:?]
	at su.nightexpress.excellentenchants.manager.tasks.AbstractEnchantPassiveTask.action(AbstractEnchantPassiveTask.java:27) ~[ExcellentEnchants-3.1.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-176]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-176]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nulli0n** [comment]
Fixed.
