### ISSUE TITLE
Task #13 for ExcellentEnchants v3.2.8 generated an exception java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Danila767** [nulli0n/ExcellentEnchants-spigot#30]
[ExcellentEnchants] Task #13 for ExcellentEnchants v3.2.8 generated an exception
java.lang.NoSuchMethodError: 'void net.minecraft.world.effect.MobEffectList.<init>(net.minecraft.world.effect.MobEffectList, int, int)'
        at su.nightexpress.excellentenchants.nms.v1_19_R1.CustomEffectInstance.<init>(CustomEffectInstance.java:18) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.nms.v1_19_R1.V1_19_R1.addEnchantmentEffect(V1_19_R1.java:33) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.api.enchantment.IEnchantPotionTemplate.addEffect(IEnchantPotionTemplate.java:81) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.manager.enchants.tool.EnchantHaste.use(EnchantHaste.java:33) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.manager.EnchantManager.lambda$updateEquippedEnchantEffects$21(EnchantManager.java:327) ~[ExcellentEnchants-3.2.8.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at su.nightexpress.excellentenchants.manager.EnchantManager.updateEquippedEnchantEffects(EnchantManager.java:325) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.manager.tasks.EnchantEffectPassiveTask.apply(EnchantEffectPassiveTask.java:20) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.manager.tasks.AbstractEnchantPassiveTask.action(AbstractEnchantPassiveTask.java:28) ~[ExcellentEnchants-3.2.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1475) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by nulli0n** [comment]
Fixed. Redownload please.
