### ISSUE TITLE
[14:21:11 ERROR]: Could not pass event PlayerQuitEvent to ExcellentEnchants v3.2.8

### ISSUE THREAD

**Issue by Danila767** [nulli0n/ExcellentEnchants-spigot#31]
[14:21:11 ERROR]: Could not pass event PlayerQuitEvent to ExcellentEnchants v3.2.8
java.lang.NoSuchMethodError: 'net.minecraft.world.effect.MobEffectList net.minecraft.world.entity.EntityLiving.b(net.minecraft.world.effect.MobEffectList)'
        at su.nightexpress.excellentenchants.nms.v1_19_R1.V1_19_R1.getEnchantmentByEffect(V1_19_R1.java:40) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.manager.EnchantManager.getEnchantmentByEffect(EnchantManager.java:277) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.manager.EnchantManager.isEnchantmentEffect(EnchantManager.java:284) ~[ExcellentEnchants-3.2.8.jar:?]
        at su.nightexpress.excellentenchants.manager.listeners.EnchantGenericListener.lambda$onEnchantPotionEffectQuit$0(EnchantGenericListener.java:44) ~[ExcellentEnchants-3.2.8.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at su.nightexpress.excellentenchants.manager.listeners.EnchantGenericListener.onEnchantPotionEffectQuit(EnchantGenericListener.java:44) ~[ExcellentEnchants-3.2.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor76.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-46]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:627) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:612) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2128) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2108) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:770) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-46]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by nulli0n** [comment]
Fixed. Redownload please.
