### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to ExcellentEnchants v3.3.4

### ISSUE THREAD

**Issue by Danila767** [nulli0n/ExcellentEnchants-spigot#45]
ProtocolLib 5.0.0, Java 18, Pufferfish 1.19.3

`[19:46:22 ERROR]: Could not pass event EntityDamageByEntityEvent to ExcellentEnchants v3.3.4
java.lang.IllegalArgumentException: data should be interface org.bukkit.block.data.BlockData got class org.bukkit.Material
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.spawnParticle(CraftWorld.java:2077) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.spawnParticle(CraftWorld.java:2072) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.spawnParticle(CraftWorld.java:2061) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.CraftWorld.spawnParticle(CraftWorld.java:2056) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at su.nexmedia.engine.api.particle.SimpleParticle.play(SimpleParticle.java:152) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.particle.SimpleParticle.play(SimpleParticle.java:136) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.particle.SimpleParticle.play(SimpleParticle.java:132) ~[NexEngine.jar:?]
        at su.nightexpress.excellentenchants.enchantment.impl.armor.EnchantIceShield.onProtect(EnchantIceShield.java:78) ~[ExcellentEnchants-3.3.4.jar:?]
        at su.nightexpress.excellentenchants.enchantment.listener.EnchantHandlerListener.lambda$handleCombatArmorEnchants$1(EnchantHandlerListener.java:113) ~[ExcellentEnchants-3.3.4.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at su.nightexpress.excellentenchants.enchantment.listener.EnchantHandlerListener.handleCombatArmorEnchants(EnchantHandlerListener.java:111) ~[ExcellentEnchants-3.3.4.jar:?]
        at su.nightexpress.excellentenchants.enchantment.listener.EnchantHandlerListener.onEnchantCombatMelee(EnchantHandlerListener.java:78) ~[ExcellentEnchants-3.3.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor88.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:git-Pufferfish-61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:250) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1154) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1013) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:965) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1188) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2172) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1054) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1393) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:961) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1071) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1643) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:364) ~[?:?]
        at net.minecraft.world.entity.monster.Husk.doHurtTarget(Husk.java:56) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:130) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:121) ~[?:?]
        at net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:157) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:888) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3384) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:642) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:269) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3031) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:404) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:239) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1227) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:734) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1537) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by skyman478** [comment]
Mine is giving an similar error, but on exhaust enchant

[18:16:43] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ExcellentEnchants v3.4.0
java.lang.IllegalArgumentException: data should be class org.bukkit.inventory.ItemStack got class org.bukkit.Material
	at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.spawnParticle(CraftWorld.java:2073) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.spawnParticle(CraftWorld.java:2068) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.spawnParticle(CraftWorld.java:2057) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.spawnParticle(CraftWorld.java:2052) ~[paper-1.19.4.jar:git-Paper-540]
	at su.nexmedia.engine.api.particle.SimpleParticle.play(SimpleParticle.java:152) ~[NexEngine (1).jar:?]
	at su.nexmedia.engine.api.particle.SimpleParticle.play(SimpleParticle.java:136) ~[NexEngine (1).jar:?]
	at su.nexmedia.engine.api.particle.SimpleParticle.play(SimpleParticle.java:132) ~[NexEngine (1).jar:?]
	at su.nightexpress.excellentenchants.enchantment.impl.weapon.EnchantExhaust.onAttack(EnchantExhaust.java:71) ~[ExcellentEnchants-3.4.0.jar:?]
	at su.nightexpress.excellentenchants.enchantment.listener.EnchantHandlerListener.lambda$handleCombatWeaponEnchants$0(EnchantHandlerListener.java:96) ~[ExcellentEnchants-3.4.0.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at su.nightexpress.excellentenchants.enchantment.listener.EnchantHandlerListener.handleCombatWeaponEnchants(EnchantHandlerListener.java:94) ~[ExcellentEnchants-3.4.0.jar:?]
	at su.nightexpress.excellentenchants.enchantment.listener.EnchantHandlerListener.onEnchantCombatMelee(EnchantHandlerListener.java:77) ~[ExcellentEnchants-3.4.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor86.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-540]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-540]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:252) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1180) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1039) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:983) ~[paper-1.19.4.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1214) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2148) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1383) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1319) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2117) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2873) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2797) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-540]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-540]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by nulli0n** [comment]
Fixed in v3.4.1
