### ISSUE TITLE
[Bug Report] flame_walker not working properly

### ISSUE THREAD

**Issue by aesopcmc** [nulli0n/ExcellentEnchants-spigot#71]
**[version]**
minecraft server: Paper1.19.3
ExcellentEnchants :  v3.5.5

**[description]:**
When walking on lava with this enchantment, it will always report an error：：

**[error]**
`
[12:35:07] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to ExcellentEnchants v3.5.5
java.lang.NullPointerException: Cannot invoke "su.nightexpress.excellentenchants.nms.EnchantNMS.handleFlameWalker(org.bukkit.entity.LivingEntity, org.bukkit.Location, int)" because the return value of "su.nightexpress.excellentenchants.ExcellentEnchants.getEnchantNMS()" is null
	at su.nightexpress.excellentenchants.enchantment.impl.armor.EnchantFlameWalker.onPlayerMove(EnchantFlameWalker.java:115) ~[ExcellentEnchants-3.5.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-375]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1593) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-375]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

and :
`
[12:35:46] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ExcellentEnchants v3.5.5
java.lang.NullPointerException: Cannot invoke "su.nightexpress.excellentenchants.nms.EnchantNMS.getSpawnEgg(org.bukkit.entity.LivingEntity)" because the return value of "su.nightexpress.excellentenchants.ExcellentEnchants.getEnchantNMS()" is null
	at su.nightexpress.excellentenchants.enchantment.impl.weapon.EnchantThrifty.onKill(EnchantThrifty.java:91) ~[ExcellentEnchants-3.5.5.jar:?]
	at su.nightexpress.excellentenchants.enchantment.listener.EnchantHandlerListener.lambda$onEnchantDeath$12(EnchantHandlerListener.java:259) ~[ExcellentEnchants-3.5.5.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at su.nightexpress.excellentenchants.enchantment.listener.EnchantHandlerListener.onEnchantDeath(EnchantHandlerListener.java:257) ~[ExcellentEnchants-3.5.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-375]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:879) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1767) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1664) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1491) ~[?:?]
	at net.minecraft.world.entity.monster.EnderMan.hurt(EnderMan.java:421) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1342) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2118) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2836) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2760) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-375]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-375]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by nulli0n** [comment]
Update to the latest plugin version and at least 1.19.4
