### ISSUE TITLE
PlayerInteractEvent Error Message in Console

### ISSUE THREAD

**Issue by SlyGuy89** [nulli0n/ExcellentEnchants-spigot#81]
Been noticing this error in console since the most recent update. Not great at reading stack traces but this doesn't look like it's part of a setting I have access to..? Sorry if this has been reported already.

Functionally I haven't noticed any faults in enchantments resulting from this, but also not sure which enchants would be affected by this error.

```
09.10 01:34:18 [Server] ERROR Could not pass event PlayerInteractEvent to ExcellentEnchants v3.6.0
09.10 01:34:18 [Server] INFO java.lang.IllegalArgumentException: slot must not be null
09.10 01:34:18 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
09.10 01:34:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftInventoryPlayer.getItem(CraftInventoryPlayer.java:150) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at su.nexmedia.engine.utils.EntityUtil.lambda$getEquippedItems$0(EntityUtil.java:47) ~[NexEngine.jar:?]
09.10 01:34:18 [Server] INFO at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
09.10 01:34:18 [Server] INFO at su.nexmedia.engine.utils.EntityUtil.getEquippedItems(EntityUtil.java:46) ~[NexEngine.jar:?]
09.10 01:34:18 [Server] INFO at su.nightexpress.excellentenchants.enchantment.util.EnchantUtils.getEnchantedEquipment(EnchantUtils.java:322) ~[ExcellentEnchants-3.6.0.jar:?]
09.10 01:34:18 [Server] INFO at su.nightexpress.excellentenchants.enchantment.util.EnchantUtils.getEquipped(EnchantUtils.java:353) ~[ExcellentEnchants-3.6.0.jar:?]
09.10 01:34:18 [Server] INFO at su.nightexpress.excellentenchants.enchantment.registry.wrapper.DataGather.getEnchants(DataGather.java:27) ~[ExcellentEnchants-3.6.0.jar:?]
09.10 01:34:18 [Server] INFO at su.nightexpress.excellentenchants.enchantment.registry.wrapper.WrappedEvent.execute(WrappedEvent.java:43) ~[ExcellentEnchants-3.6.0.jar:?]
09.10 01:34:18 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
09.10 01:34:18 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
09.10 01:34:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:591) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:548) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:542) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.world.level.block.FarmBlock.fallOn(FarmBlock.java:108) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1758) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:381) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1531) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1678) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
09.10 01:34:18 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1385) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
09.10 01:34:18 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nulli0n** [comment]
Fixed.
