### ISSUE TITLE
Frequent warnings when installing MythicMobs 5.6.0

### ISSUE THREAD

**Issue by alazeprt** [nulli0n/ExcellentEnchants-spigot#96]
As the title suggests, warning message:
```
[08:19:35 WARN]: [ExcellentEnchants] Task #8074 for ExcellentEnchants v3.6.5 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class su.nightexpress.excellentenchants.hook.impl.MythicMobsHook
        at su.nightexpress.excellentenchants.enchantment.listener.EnchantGenericListener.lambda$onEnchantPopulateSpawn$10(EnchantGenericListener.java:237) ~[ExcellentEnchants-3.6.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:95) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1626) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1509) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: io/lumine/mythic/bukkit/MythicBukkit [in thread "Server thread"]
        at su.nightexpress.excellentenchants.hook.impl.MythicMobsHook.<clinit>(MythicMobsHook.java:9) ~[ExcellentEnchants-3.6.5.jar:?]
        ... 9 more
[08:19:35 WARN]: [ExcellentEnchants] Task #8075 for ExcellentEnchants v3.6.5 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class su.nightexpress.excellentenchants.hook.impl.MythicMobsHook
        at su.nightexpress.excellentenchants.enchantment.listener.EnchantGenericListener.lambda$onEnchantPopulateSpawn$10(EnchantGenericListener.java:237) ~[ExcellentEnchants-3.6.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:95) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1626) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1509) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: io/lumine/mythic/bukkit/MythicBukkit [in thread "Server thread"]
        at su.nightexpress.excellentenchants.hook.impl.MythicMobsHook.<clinit>(MythicMobsHook.java:9) ~[ExcellentEnchants-3.6.5.jar:?]
        ... 9 more
[08:19:35 WARN]: [ExcellentEnchants] Task #8076 for ExcellentEnchants v3.6.5 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class su.nightexpress.excellentenchants.hook.impl.MythicMobsHook
        at su.nightexpress.excellentenchants.enchantment.listener.EnchantGenericListener.lambda$onEnchantPopulateSpawn$10(EnchantGenericListener.java:237) ~[ExcellentEnchants-3.6.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:95) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1626) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1509) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e52beae"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: io/lumine/mythic/bukkit/MythicBukkit [in thread "Server thread"]
        at su.nightexpress.excellentenchants.hook.impl.MythicMobsHook.<clinit>(MythicMobsHook.java:9) ~[ExcellentEnchants-3.6.5.jar:?]
        ... 9 more
```

**Comment by nulli0n** [comment]
Your MythicMobs not working at all, fix it.
